package observe

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"sync"
	"sync/atomic"
	"time"

	"github.com/jenaiz/pcke/internal/kdb/event"
	"github.com/jenaiz/pcke/internal/kdb/tx"
	pckelog "github.com/jenaiz/pcke/internal/log"
)

// Writer is the minimal *event.Store surface the collector needs. The
// interface lets tests substitute a fake without spinning up a kdb.
type Writer interface {
	// AppendInTx writes the next version of e through the supplied
	// open WriteTx. The forward record (and, for Links, the paired lr:
	// entry) is staged on Put; durability is bounded by group commit.
	AppendInTx(wtx *tx.WriteTx, e event.Event) ([]byte, error)
}

// Updater is the *kdb.DB surface used to run a single WriteTx. It is
// satisfied by *kdb.DB and by event.StoreDB.
type Updater interface {
	Update(ctx context.Context, fn func(*tx.WriteTx) error) error
}

// grower is the optional Updater extension the collector uses to add
// free pages when a batch exhausts the freelist. *kdb.DB satisfies it.
// Updaters without Grow() fail the batch on out-of-pages.
type grower interface {
	Grow() error
}

// SessionStart is the record produced when an agent session is first
// observed. The Observation is written once per session; subsequent
// Calls on the same session re-use it via a belongs_to / contains pair.
type SessionStart struct {
	// UUID is the session identifier supplied by the caller.
	UUID string
	// Label is an optional human-readable tag (e.g. the client name);
	// stored as Observation.Subject when non-empty.
	Label string
	// At is the wall-clock time the session started. Zero means "use
	// time.Now at write time"; tests pin a deterministic value.
	At time.Time
}

// Call records a single MCP tool invocation: which tool ran, what refs
// it served, and which session it belongs to.
//
// Served may be empty (e.g. a tool that mutated state without
// returning refs); in that case only the call observation + belongs_to
// link are written.
type Call struct {
	// UUID identifies this call. Generated by the caller (usually a
	// UUIDv4 or ULID); the collector treats it as an opaque string.
	UUID string
	// SessionUUID is the UUID of the parent Session observation.
	SessionUUID string
	// Tool is the MCP tool name (e.g. "get_context_for_file").
	Tool string
	// Served lists the typed refs surfaced by the response (e.g.
	// "e:internal/kdb/db.go", "d:adr-0008"). Empty refs are dropped.
	Served []string
	// At is the wall-clock time the call completed. Zero means "use
	// time.Now at write time".
	At time.Time
}

// Options controls Collector buffering and durability.
type Options struct {
	// BufferSize is the pending-record capacity. Defaults to 1024.
	BufferSize int
	// MaxBatch caps how many records are merged into a single kdb
	// transaction. Defaults to 64.
	MaxBatch int
	// FlushInterval forces a flush when the buffer is non-empty but
	// has not reached MaxBatch in this duration. Defaults to 50ms.
	FlushInterval time.Duration
	// Logger is the slog destination for warnings (dropped records,
	// write errors). nil → pckelog.Logger("observe").
	Logger *slog.Logger
	// Now is the timestamp source. nil → time.Now.UTC. Substituted in
	// tests for determinism.
	Now func() time.Time
}

// Collector buffers SessionStart + Call records and flushes them as
// Observation + Link events via the supplied Updater. The zero value
// is not usable; construct with New.
type Collector struct {
	updater Updater
	store   Writer
	opts    Options
	log     *slog.Logger
	now     func() time.Time

	ch         chan record
	closed     atomic.Bool
	wg         sync.WaitGroup
	disabled   atomic.Bool
	dropped    atomic.Int64
	writeErrs  atomic.Int64
	writtenCnt atomic.Int64

	// sessionsSeen guards the once-per-session SessionStart write so we
	// don't re-append a Session observation on every Call.
	sessionsSeen sync.Map // map[string]struct{}
}

// recordKind discriminates the queued items.
type recordKind uint8

const (
	recordSession recordKind = 1
	recordCall    recordKind = 2
)

type record struct {
	kind recordKind
	sess SessionStart
	call Call
}

// New constructs a Collector backed by store. The Updater is used for
// the per-batch kdb transaction. Caller must Close the collector to
// drain pending records on shutdown.
func New(updater Updater, store Writer, opts Options) *Collector {
	if opts.BufferSize <= 0 {
		opts.BufferSize = 1024
	}
	if opts.MaxBatch <= 0 {
		opts.MaxBatch = 64
	}
	if opts.FlushInterval <= 0 {
		opts.FlushInterval = 50 * time.Millisecond
	}
	logger := opts.Logger
	if logger == nil {
		logger = pckelog.Logger("observe")
	}
	now := opts.Now
	if now == nil {
		now = func() time.Time { return time.Now().UTC() }
	}

	c := &Collector{
		updater: updater,
		store:   store,
		opts:    opts,
		log:     logger,
		now:     now,
		ch:      make(chan record, opts.BufferSize),
	}
	c.wg.Add(1)
	go c.run()
	return c
}

// RecordSessionStart enqueues a session-start observation. Non-blocking:
// if the buffer is full or the collector is closed/disabled the call
// returns immediately with no error and increments the drop counter.
func (c *Collector) RecordSessionStart(s SessionStart) {
	if c == nil || c.disabled.Load() || c.closed.Load() {
		return
	}
	if s.UUID == "" {
		return
	}
	select {
	case c.ch <- record{kind: recordSession, sess: s}:
	default:
		c.dropped.Add(1)
	}
}

// RecordCall enqueues a single tool-call observation. Non-blocking:
// see RecordSessionStart for full semantics.
//
// If the parent SessionStart was never recorded the collector still
// writes the call and a belongs_to edge — the absent session
// observation is treated as "best-effort observation". Downstream
// readers compose what they have.
func (c *Collector) RecordCall(call Call) {
	if c == nil || c.disabled.Load() || c.closed.Load() {
		return
	}
	if call.UUID == "" || call.Tool == "" {
		return
	}
	select {
	case c.ch <- record{kind: recordCall, call: call}:
	default:
		c.dropped.Add(1)
	}
}

// SetEnabled toggles observation writing for the running collector.
// Disabling drops in-flight enqueues but does not stop the flush loop;
// future enqueues short-circuit until the collector is re-enabled.
//
// Re-enables are safe; the collector picks up new records on the next
// flush tick.
func (c *Collector) SetEnabled(enabled bool) {
	if c == nil {
		return
	}
	c.disabled.Store(!enabled)
}

// Close drains pending records, blocks until the flush loop exits, and
// returns any final write error. Subsequent Record* calls are no-ops.
func (c *Collector) Close() error {
	if c == nil || !c.closed.CompareAndSwap(false, true) {
		return nil
	}
	close(c.ch)
	c.wg.Wait()
	return nil
}

// Stats returns a snapshot of collector counters. Useful for tests +
// observability. The returned struct is a value copy.
type Stats struct {
	Written   int64
	Dropped   int64
	WriteErrs int64
}

// Stats returns a snapshot of running counters.
func (c *Collector) Stats() Stats {
	if c == nil {
		return Stats{}
	}
	return Stats{
		Written:   c.writtenCnt.Load(),
		Dropped:   c.dropped.Load(),
		WriteErrs: c.writeErrs.Load(),
	}
}

// run is the flush loop. It batches up to MaxBatch records or waits at
// most FlushInterval before flushing whatever it has.
func (c *Collector) run() {
	defer c.wg.Done()

	ticker := time.NewTicker(c.opts.FlushInterval)
	defer ticker.Stop()

	batch := make([]record, 0, c.opts.MaxBatch)

	flush := func() {
		if len(batch) == 0 {
			return
		}
		if err := c.writeBatch(batch); err != nil {
			c.writeErrs.Add(1)
			c.log.Warn("flush failed", "err", err, "batch_size", len(batch))
		}
		batch = batch[:0]
	}

	for {
		select {
		case r, ok := <-c.ch:
			if !ok {
				flush()
				return
			}
			batch = append(batch, r)
			if len(batch) >= c.opts.MaxBatch {
				flush()
			}
		case <-ticker.C:
			flush()
		}
	}
}

// pagesPerRecord is a conservative upper bound on the number of new
// pages a single record can allocate in one transaction. Each Call
// record writes 1 Observation + up to ~10 Links + each row's overflow
// chain (the overflow threshold is ~6 bytes, so every encoded event
// uses at least 1 overflow page). 32 leaves headroom for btree splits.
const pagesPerRecord = 32

// writeBatch persists batch atomically. All records of the same
// session join the same WriteTx so the contains/belongs_to edges land
// together with their endpoints.
//
// kdb does not auto-grow inside a write transaction. To prevent the
// freelist from running dry mid-tx (and triggering a partial WAL
// record that would fail to replay), we pre-grow the file enough to
// satisfy the entire batch BEFORE opening the tx. The growth path
// updates the in-memory freelist eagerly; the subsequent Update's
// commitMeta persists the new size + freelist root so re-opens see
// the same state.
//
// If the Updater does not implement Grow (e.g. test doubles), the
// batch is attempted as-is — small batches succeed and large batches
// surface the freelist error to the caller.
func (c *Collector) writeBatch(batch []record) error {
	if c.disabled.Load() {
		return nil
	}
	if g, ok := c.updater.(grower); ok {
		needed := (len(batch)*pagesPerRecord + (growthChunkPages - 1)) / growthChunkPages
		for i := 0; i < needed; i++ {
			if err := g.Grow(); err != nil {
				return fmt.Errorf("observe: pre-grow %d/%d: %w", i+1, needed, err)
			}
		}
	}

	ctx := context.Background()
	err := c.updater.Update(ctx, func(wtx *tx.WriteTx) error {
		for _, r := range batch {
			switch r.kind {
			case recordSession:
				if err := c.writeSession(wtx, r.sess); err != nil {
					return fmt.Errorf("session %q: %w", r.sess.UUID, err)
				}
			case recordCall:
				if err := c.writeCall(wtx, r.call); err != nil {
					return fmt.Errorf("call %q: %w", r.call.UUID, err)
				}
			default:
				return fmt.Errorf("unknown record kind %d", r.kind)
			}
		}
		return nil
	})
	if err != nil {
		return err
	}
	c.writtenCnt.Add(int64(len(batch)))
	return nil
}

// growthChunkPages mirrors kdb.GrowthChunk locally to avoid an import
// cycle (observe imports kdb/event, kdb/tx, and the test files build
// against *kdb.DB). Keep in sync with internal/kdb/db.go.
const growthChunkPages = 16

// writeSession appends the Session observation if we have not already
// seen its UUID in this process lifetime. Idempotent within a process;
// a restart may write a duplicate (a "session resumed" pattern),
// which is acceptable — the version chain absorbs it.
func (c *Collector) writeSession(wtx *tx.WriteTx, s SessionStart) error {
	if _, dup := c.sessionsSeen.LoadOrStore(s.UUID, struct{}{}); dup {
		return nil
	}
	obs := &event.Observation{
		OID:     event.SessionOID(s.UUID),
		Action:  event.ActionSession,
		Subject: s.Label,
		Hdr:     event.Header{CreatedAt: c.stamp(s.At)},
	}
	if _, err := c.store.AppendInTx(wtx, obs); err != nil {
		return err
	}
	return nil
}

// writeCall appends the ToolCall observation plus its edges:
//   - contains : session → call
//   - belongs_to: call    → session
//   - served    : call    → each served ref (e:/d:/...)
//
// The session must be writable before the link can be appended; if the
// SessionStart has not been queued we still write a Session observation
// here so the contains edge resolves.
func (c *Collector) writeCall(wtx *tx.WriteTx, call Call) error {
	// Ensure a session observation exists before linking.
	if err := c.writeSession(wtx, SessionStart{UUID: call.SessionUUID, At: call.At}); err != nil {
		return fmt.Errorf("ensure session: %w", err)
	}

	obs := &event.Observation{
		OID:     event.CallOID(call.UUID),
		Action:  event.ActionCall,
		Subject: call.Tool,
		Hdr:     event.Header{CreatedAt: c.stamp(call.At)},
	}
	if _, err := c.store.AppendInTx(wtx, obs); err != nil {
		return err
	}

	sessRef := event.SessionRef(call.SessionUUID)
	callRef := event.CallRef(call.UUID)

	links := []*event.Link{
		{SrcRef: sessRef, EdgeType: event.EdgeContains, DstRef: callRef},
		{SrcRef: callRef, EdgeType: event.EdgeBelongsTo, DstRef: sessRef},
	}
	for _, ref := range call.Served {
		if ref == "" {
			continue
		}
		links = append(links, &event.Link{
			SrcRef:   callRef,
			EdgeType: event.EdgeServed,
			DstRef:   ref,
		})
	}
	for _, l := range links {
		l.Hdr = event.Header{CreatedAt: c.stamp(call.At)}
		if _, err := c.store.AppendInTx(wtx, l); err != nil {
			return err
		}
	}
	return nil
}

// stamp returns at when non-zero, else the configured clock value.
func (c *Collector) stamp(at time.Time) time.Time {
	if !at.IsZero() {
		return at
	}
	return c.now()
}

// ErrClosed is returned for operations attempted after Close. Kept for
// future expansion of the public API (no current call site returns it).
var ErrClosed = errors.New("observe: collector closed")
