package output

import (
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/jenaiz/pcke/internal/analysis"
)

// renderCopilotInstructions generates the .github/copilot-instructions.md
// file with smart, ranked project context for GitHub Copilot.
func renderCopilotInstructions(
	nodes []analysis.KnowledgeNode,
	modules map[string][]analysis.KnowledgeNode,
) string {
	var b strings.Builder
	b.WriteString("# Copilot Instructions\n\n")
	b.WriteString("> Auto-generated by `pcke sync`. Do not edit manually.\n\n")

	renderCopilotOverview(&b, nodes)
	renderCopilotConstraints(&b, nodes)
	renderCopilotConventions(&b, nodes, modules)
	renderCopilotFocusAreas(&b, nodes)
	renderCopilotPatterns(&b, nodes, modules)
	renderCopilotModules(&b, modules)

	return b.String()
}

func renderCopilotOverview(b *strings.Builder, nodes []analysis.KnowledgeNode) {
	b.WriteString("## Project Overview\n\n")
	langs := countLanguages(nodes)
	if len(langs) > 0 {
		b.WriteString("Languages: ")
		parts := make([]string, 0, len(langs))
		for _, lc := range langs {
			parts = append(parts, fmt.Sprintf("%s (%d files)", lc.name, lc.count))
		}
		b.WriteString(strings.Join(parts, ", "))
		b.WriteString("\n\n")
	}
}

func renderCopilotConstraints(b *strings.Builder, nodes []analysis.KnowledgeNode) {
	constraints := extractConstraintNodes(nodes)
	if len(constraints) > 0 {
		b.WriteString("## Active Constraints (MUST follow)\n\n")
		for _, c := range constraints {
			scope := "global"
			if c.Module != "" {
				scope = c.Module
			}
			fmt.Fprintf(b, "- %s [%s]\n", c.Name, scope)
		}
		b.WriteString("\n")
	}
}

func renderCopilotConventions(b *strings.Builder, nodes []analysis.KnowledgeNode, modules map[string][]analysis.KnowledgeNode) {
	conventions := extractConventions(nodes, modules)
	if len(conventions) > 0 {
		b.WriteString("## Conventions (SHOULD follow)\n\n")
		for _, c := range conventions {
			fmt.Fprintf(b, "- %s\n", c)
		}
		b.WriteString("\n")
	}
}

func renderCopilotFocusAreas(b *strings.Builder, nodes []analysis.KnowledgeNode) {
	focusAreas := extractFocusAreas(nodes)
	if len(focusAreas) > 0 {
		b.WriteString("## Current Focus Areas\n\n")
		for _, fa := range focusAreas {
			fmt.Fprintf(b, "- %s\n", fa)
		}
		b.WriteString("\n")
	}
}

func renderCopilotPatterns(b *strings.Builder, nodes []analysis.KnowledgeNode, modules map[string][]analysis.KnowledgeNode) {
	patterns := extractPatterns(nodes, modules)
	if len(patterns) > 0 {
		b.WriteString("## Common Patterns\n\n")
		for _, p := range patterns {
			fmt.Fprintf(b, "- %s\n", p)
		}
		b.WriteString("\n")
	}
}

func renderCopilotModules(b *strings.Builder, modules map[string][]analysis.KnowledgeNode) {
	if len(modules) == 0 {
		return
	}
	b.WriteString("## Modules\n\n")
	modNames := sortedModuleNames(modules)
	limit := 10
	if len(modNames) < limit {
		limit = len(modNames)
	}
	for _, name := range modNames[:limit] {
		fmt.Fprintf(b, "- `%s` (%d files)\n", name, len(modules[name]))
	}
	if len(modNames) > 10 {
		fmt.Fprintf(b, "- ... and %d more modules\n", len(modNames)-10)
	}
	b.WriteString("\n")
}

// extractConstraintNodes returns nodes that are rule/constraint type with must severity.
func extractConstraintNodes(nodes []analysis.KnowledgeNode) []analysis.KnowledgeNode {
	var constraints []analysis.KnowledgeNode
	for _, n := range nodes {
		if n.Type == "rule" || n.Class == "constraint" {
			constraints = append(constraints, n)
		}
	}
	return constraints
}

// extractConventions infers conventions from code patterns with >80% adoption.
func extractConventions(nodes []analysis.KnowledgeNode, modules map[string][]analysis.KnowledgeNode) []string {
	var conventions []string

	// Check for Go conventions.
	goFiles := 0
	hasTests := 0
	for _, n := range nodes {
		if n.Language == "Go" {
			goFiles++
			if strings.HasSuffix(n.FilePath, "_test.go") {
				hasTests++
			}
		}
	}
	if goFiles > 0 && float64(hasTests)/float64(goFiles) > 0.3 {
		conventions = append(conventions, "Test files colocated with source (_test.go pattern)")
	}

	// Check for module structure convention.
	if len(modules) > 3 {
		internalCount := 0
		for mod := range modules {
			if strings.HasPrefix(mod, "internal/") {
				internalCount++
			}
		}
		if float64(internalCount)/float64(len(modules)) > 0.5 {
			conventions = append(conventions, "Internal packages for encapsulation (internal/ prefix)")
		}
	}

	return conventions
}

// extractFocusAreas identifies recently active modules (last 14 days).
func extractFocusAreas(nodes []analysis.KnowledgeNode) []string {
	cutoff := time.Now().AddDate(0, 0, -14)
	moduleCounts := make(map[string]int)
	for _, n := range nodes {
		if n.UpdatedAt.After(cutoff) && n.Module != "" {
			moduleCounts[n.Module]++
		}
	}

	type modCount struct {
		name  string
		count int
	}
	var sorted []modCount
	for name, count := range moduleCounts {
		sorted = append(sorted, modCount{name, count})
	}
	sort.Slice(sorted, func(i, j int) bool {
		return sorted[i].count > sorted[j].count
	})

	var areas []string
	limit := 5
	if len(sorted) < limit {
		limit = len(sorted)
	}
	for _, mc := range sorted[:limit] {
		areas = append(areas, fmt.Sprintf("`%s` — %d recent changes", mc.name, mc.count))
	}
	return areas
}

// extractPatterns detects common code patterns from entity analysis.
func extractPatterns(nodes []analysis.KnowledgeNode, _ map[string][]analysis.KnowledgeNode) []string {
	var patterns []string

	// Detect entry points.
	for _, n := range nodes {
		if n.Class == "entrypoint" || n.Class == "main" {
			patterns = append(patterns, fmt.Sprintf("Entry point: `%s`", n.FilePath))
		}
	}

	// Detect common entity kinds.
	kindCounts := make(map[string]int)
	for _, n := range nodes {
		for _, e := range n.Entities {
			kindCounts[string(e.Kind)]++
		}
	}
	for kind, count := range kindCounts {
		if count > 10 {
			patterns = append(patterns, fmt.Sprintf("%s: %d instances across codebase", kind, count))
		}
	}

	if len(patterns) > 8 {
		patterns = patterns[:8]
	}
	return patterns
}

// renderClaudeInstructions generates the .claude/CLAUDE.md file with
// project context for Anthropic Claude.
func renderClaudeInstructions(
	nodes []analysis.KnowledgeNode,
	modules map[string][]analysis.KnowledgeNode,
) string {
	var b strings.Builder
	b.WriteString("# CLAUDE\n\n")
	b.WriteString("> Auto-generated by `pcke sync`. Do not edit manually.\n\n")

	b.WriteString("## Project Overview\n\n")
	langs := countLanguages(nodes)
	if len(langs) > 0 {
		b.WriteString("Languages: ")
		parts := make([]string, 0, len(langs))
		for _, lc := range langs {
			parts = append(parts, fmt.Sprintf("%s (%d files)", lc.name, lc.count))
		}
		b.WriteString(strings.Join(parts, ", "))
		b.WriteString("\n\n")
	}

	if len(modules) > 0 {
		b.WriteString("## Modules\n\n")
		for _, name := range sortedModuleNames(modules) {
			fmt.Fprintf(&b, "- `%s` (%d files)\n", name, len(modules[name]))
		}
		b.WriteString("\n")
	}

	return b.String()
}
