package output

import (
	"fmt"
	"strings"

	"github.com/jenaiz/pcke/internal/analysis"
)

// renderCopilotInstructions generates the .github/copilot-instructions.md
// file with project context for GitHub Copilot.
func renderCopilotInstructions(
	nodes []analysis.KnowledgeNode,
	modules map[string][]analysis.KnowledgeNode,
	topo *Topology,
) string {
	return renderAgentFile("# Copilot Instructions", nodes, modules, topo)
}

// renderClaudeInstructions generates the .claude/CLAUDE.md file with
// project context for Anthropic Claude.
func renderClaudeInstructions(
	nodes []analysis.KnowledgeNode,
	modules map[string][]analysis.KnowledgeNode,
	topo *Topology,
) string {
	return renderAgentFile("# CLAUDE", nodes, modules, topo)
}

// renderAgentFile is the shared body for the Copilot and Claude
// instruction files. The "Architecture Quick Reference" block sits
// between the project overview and the per-module file counts: it
// gives the agent a graph-derived map of where to start before falling
// back to the (less informative) module-count list.
func renderAgentFile(
	header string,
	nodes []analysis.KnowledgeNode,
	modules map[string][]analysis.KnowledgeNode,
	topo *Topology,
) string {
	var b strings.Builder
	fmt.Fprintf(&b, "%s\n\n", header)
	b.WriteString("> Auto-generated by `pcke sync`. Do not edit manually.\n\n")

	b.WriteString("## Project Overview\n\n")
	langs := countLanguages(nodes)
	if len(langs) > 0 {
		b.WriteString("Languages: ")
		parts := make([]string, 0, len(langs))
		for _, lc := range langs {
			parts = append(parts, fmt.Sprintf("%s (%d files)", lc.name, lc.count))
		}
		b.WriteString(strings.Join(parts, ", "))
		b.WriteString("\n\n")
	}

	if quickRef := renderArchQuickReference(topo); quickRef != "" {
		b.WriteString(quickRef)
	}

	if len(modules) > 0 {
		b.WriteString("## Modules\n\n")
		for _, name := range sortedModuleNames(modules) {
			fmt.Fprintf(&b, "- `%s` (%d files)\n", name, len(modules[name]))
		}
		b.WriteString("\n")
	}

	return b.String()
}
