package output

import (
	"fmt"
	"strings"

	"github.com/jenaiz/pcke/internal/analysis"
)

// renderCopilotInstructions generates the .github/copilot-instructions.md
// file with project context for GitHub Copilot.
func renderCopilotInstructions(
	nodes []analysis.KnowledgeNode,
	modules map[string][]analysis.KnowledgeNode,
) string {
	var b strings.Builder
	b.WriteString("# Copilot Instructions\n\n")
	b.WriteString("> Auto-generated by `pcke sync`. Do not edit manually.\n\n")

	b.WriteString("## Project Overview\n\n")
	langs := countLanguages(nodes)
	if len(langs) > 0 {
		b.WriteString("Languages: ")
		parts := make([]string, 0, len(langs))
		for _, lc := range langs {
			parts = append(parts, fmt.Sprintf("%s (%d files)", lc.name, lc.count))
		}
		b.WriteString(strings.Join(parts, ", "))
		b.WriteString("\n\n")
	}

	if len(modules) > 0 {
		b.WriteString("## Modules\n\n")
		for _, name := range sortedModuleNames(modules) {
			fmt.Fprintf(&b, "- `%s` (%d files)\n", name, len(modules[name]))
		}
		b.WriteString("\n")
	}

	return b.String()
}

// renderClaudeInstructions generates the .claude/CLAUDE.md file with
// project context for Anthropic Claude.
func renderClaudeInstructions(
	nodes []analysis.KnowledgeNode,
	modules map[string][]analysis.KnowledgeNode,
) string {
	var b strings.Builder
	b.WriteString("# CLAUDE\n\n")
	b.WriteString("> Auto-generated by `pcke sync`. Do not edit manually.\n\n")

	b.WriteString("## Project Overview\n\n")
	langs := countLanguages(nodes)
	if len(langs) > 0 {
		b.WriteString("Languages: ")
		parts := make([]string, 0, len(langs))
		for _, lc := range langs {
			parts = append(parts, fmt.Sprintf("%s (%d files)", lc.name, lc.count))
		}
		b.WriteString(strings.Join(parts, ", "))
		b.WriteString("\n\n")
	}

	if len(modules) > 0 {
		b.WriteString("## Modules\n\n")
		for _, name := range sortedModuleNames(modules) {
			fmt.Fprintf(&b, "- `%s` (%d files)\n", name, len(modules[name]))
		}
		b.WriteString("\n")
	}

	return b.String()
}
