package output

import (
	"fmt"
	"sort"
	"strings"

	"github.com/jenaiz/pcke/internal/analysis"
)

// renderArchitecture generates the ARCHITECTURE.md content from the knowledge
// nodes, showing the module map, tech stack, and file classification summary.
func renderArchitecture(nodes []analysis.KnowledgeNode) string {
	var b strings.Builder
	b.WriteString("# Architecture\n\n")
	b.WriteString("> Auto-generated by `pcke sync`. Do not edit manually.\n\n")

	// Tech stack (languages).
	langs := countLanguages(nodes)
	if len(langs) > 0 {
		b.WriteString("## Tech Stack\n\n")
		for _, lc := range langs {
			fmt.Fprintf(&b, "- **%s**: %d files\n", lc.name, lc.count)
		}
		b.WriteString("\n")
	}

	// Module map.
	modules := groupByModule(nodes)
	if len(modules) > 0 {
		b.WriteString("## Modules\n\n")
		for _, name := range sortedModuleNames(modules) {
			modNodes := modules[name]
			fmt.Fprintf(&b, "### `%s`\n\n", name)
			fmt.Fprintf(&b, "%d files\n\n", len(modNodes))
		}
	}

	// File classification summary.
	classes := countClasses(nodes)
	if len(classes) > 0 {
		b.WriteString("## File Classification\n\n")
		b.WriteString("| Class | Count |\n|-------|-------|\n")
		for _, cc := range classes {
			fmt.Fprintf(&b, "| %s | %d |\n", cc.name, cc.count)
		}
		b.WriteString("\n")
	}

	return b.String()
}

type nameCount struct {
	name  string
	count int
}

func countLanguages(nodes []analysis.KnowledgeNode) []nameCount {
	m := map[string]int{}
	for _, n := range nodes {
		if n.Language != "" {
			m[n.Language]++
		}
	}
	return sortedNameCounts(m)
}

func countClasses(nodes []analysis.KnowledgeNode) []nameCount {
	m := map[string]int{}
	for _, n := range nodes {
		if n.Class != "" {
			m[n.Class]++
		}
	}
	return sortedNameCounts(m)
}

func sortedNameCounts(m map[string]int) []nameCount {
	result := make([]nameCount, 0, len(m))
	for name, count := range m {
		result = append(result, nameCount{name, count})
	}
	sort.Slice(result, func(i, j int) bool {
		if result[i].count != result[j].count {
			return result[i].count > result[j].count
		}
		return result[i].name < result[j].name
	})
	return result
}
