package output

import (
	"strings"

	"github.com/jenaiz/pcke/internal/analysis"
)

// RenderConstraints generates the CONSTRAINTS.md content listing engineering
// rules inferred from the project configuration.
func RenderConstraints(nodes []analysis.KnowledgeNode) string {
	var b strings.Builder
	b.WriteString("# Constraints\n\n")
	b.WriteString("> Auto-generated by `pcke sync`. Do not edit manually.\n\n")

	// Detect Go project by presence of .go files.
	hasGo := false
	for _, n := range nodes {
		if n.Language == "Go" {
			hasGo = true
			break
		}
	}

	if hasGo {
		b.WriteString("## Go\n\n")
		b.WriteString("- All code must compile with `go build ./...`\n")
		b.WriteString("- Tests must pass with `go test -race ./...`\n")
		b.WriteString("- Linting via golangci-lint (see `.golangci.yml`)\n")
		b.WriteString("\n")
	}

	// Infrastructure files imply deployment constraints.
	hasInfra := false
	for _, n := range nodes {
		if n.Class == "infra" {
			hasInfra = true
			break
		}
	}

	if hasInfra {
		b.WriteString("## Infrastructure\n\n")
		b.WriteString("- Infrastructure-as-code files detected; changes require review\n")
		b.WriteString("\n")
	}

	if !hasGo && !hasInfra {
		b.WriteString("No specific constraints detected.\n")
	}

	return b.String()
}
