package output

import (
	"fmt"
	"strings"

	"github.com/jenaiz/pcke/internal/analysis"
)

// renderConventions generates the CONVENTIONS.md content describing detected
// patterns and naming conventions in the codebase.
func renderConventions(nodes []analysis.KnowledgeNode) string {
	var b strings.Builder
	b.WriteString("# Conventions\n\n")
	b.WriteString("> Auto-generated by `pcke sync`. Do not edit manually.\n\n")

	// Language distribution.
	langs := countLanguages(nodes)
	if len(langs) > 0 {
		b.WriteString("## Languages\n\n")
		for _, lc := range langs {
			fmt.Fprintf(&b, "- %s (%d files)\n", lc.name, lc.count)
		}
		b.WriteString("\n")
	}

	// Test file ratio.
	var testCount, sourceCount int
	for _, n := range nodes {
		switch n.Class {
		case "test":
			testCount++
		case "source":
			sourceCount++
		}
	}
	if sourceCount > 0 {
		ratio := float64(testCount) / float64(sourceCount)
		fmt.Fprintf(&b, "## Test Coverage\n\n")
		fmt.Fprintf(&b, "- Test/source ratio: %.2f (%d test files / %d source files)\n\n", ratio, testCount, sourceCount)
	}

	return b.String()
}
