package output

import (
	"strings"

	"github.com/jenaiz/pcke/internal/analysis"
)

// renderDecisions generates the DECISIONS.md content. In Phase 0 this is a
// placeholder that lists documentation files found in the scan.
func renderDecisions(nodes []analysis.KnowledgeNode) string {
	var b strings.Builder
	b.WriteString("# Decisions\n\n")
	b.WriteString("> Auto-generated by `pcke sync`. Do not edit manually.\n\n")

	var docs []analysis.KnowledgeNode
	for _, n := range nodes {
		if n.Class == "doc" {
			docs = append(docs, n)
		}
	}

	if len(docs) == 0 {
		b.WriteString("No decision documents detected.\n")
		return b.String()
	}

	b.WriteString("## Documentation Files\n\n")
	for _, d := range docs {
		b.WriteString("- `" + d.FilePath + "`\n")
	}
	b.WriteString("\n")

	return b.String()
}
