package output

import (
	"context"
	"fmt"
	"sort"
	"strings"

	"github.com/jenaiz/pcke/internal/kdb"
	"github.com/jenaiz/pcke/internal/kdb/event"
)

// DecisionInfo is a flattened, render-ready view of a [event.Decision]:
// the latest active version plus the file paths it reaches via
// decision_link edges.
type DecisionInfo struct {
	ID       string
	Title    string
	Severity event.Severity
	Scope    event.Scope
	Source   string
	Files    []string
}

// LoadDecisions reads every active decision from the typed-event log and
// attaches the file paths linked to it via decision_link edges.
//
// Two passes over the log, mirroring [ComputeTopology]: decisions first
// (so files can be attributed as they're discovered), then links.
func LoadDecisions(ctx context.Context, db *kdb.DB) ([]DecisionInfo, error) {
	store := event.New(db)

	byID := map[string]*DecisionInfo{}
	if err := store.IterateKind(ctx, event.KindDecision, func(e event.Event) error {
		d, ok := e.(*event.Decision)
		if !ok || d.Header().Lifecycle != event.LifecycleActive {
			return nil
		}
		byID[d.DID] = &DecisionInfo{
			ID:       d.DID,
			Title:    d.Title,
			Severity: d.Severity,
			Scope:    d.Scope,
			Source:   d.Source,
		}
		return nil
	}); err != nil {
		return nil, fmt.Errorf("output: iterate decisions: %w", err)
	}

	if err := store.IterateKind(ctx, event.KindLink, func(e event.Event) error {
		l, ok := e.(*event.Link)
		if !ok || l.EdgeType != "decision_link" {
			return nil
		}
		did, ok := strings.CutPrefix(l.DstRef, "d:")
		if !ok {
			return nil
		}
		info, ok := byID[did]
		if !ok {
			return nil
		}
		info.Files = append(info.Files, strings.TrimPrefix(l.SrcRef, "e:"))
		return nil
	}); err != nil {
		return nil, fmt.Errorf("output: iterate decision links: %w", err)
	}

	decisions := make([]DecisionInfo, 0, len(byID))
	for _, info := range byID {
		sort.Strings(info.Files)
		decisions = append(decisions, *info)
	}
	sort.Slice(decisions, func(i, j int) bool { return decisions[i].ID < decisions[j].ID })
	return decisions, nil
}

// FilterDecisionsByModule returns decisions scoped to the whole project
// plus decisions linked to at least one file under module.
func FilterDecisionsByModule(decisions []DecisionInfo, module string) []DecisionInfo {
	var filtered []DecisionInfo
	for _, d := range decisions {
		if d.Scope == event.ScopeGlobal {
			filtered = append(filtered, d)
			continue
		}
		for _, f := range d.Files {
			if f == module || strings.HasPrefix(f, module+"/") {
				filtered = append(filtered, d)
				break
			}
		}
	}
	return filtered
}

// severityRank orders must before should before may; unknown severities
// sort last.
func severityRank(s event.Severity) int {
	switch s {
	case event.SeverityMust:
		return 0
	case event.SeverityShould:
		return 1
	case event.SeverityMay:
		return 2
	default:
		return 3
	}
}

func severityHeading(s event.Severity) string {
	switch s {
	case event.SeverityMust:
		return "Must"
	case event.SeverityShould:
		return "Should"
	case event.SeverityMay:
		return "May"
	default:
		return "Unspecified"
	}
}

// RenderDecisions generates the DECISIONS.md content: every active
// decision from the typed-event log, grouped by severity and annotated
// with its source and linked files.
func RenderDecisions(decisions []DecisionInfo) string {
	var b strings.Builder
	b.WriteString("# Decisions\n\n")
	b.WriteString("> Auto-generated by `pcke sync`. Do not edit manually.\n\n")

	if len(decisions) == 0 {
		b.WriteString("No decisions recorded yet.\n")
		return b.String()
	}

	sorted := append([]DecisionInfo(nil), decisions...)
	sort.SliceStable(sorted, func(i, j int) bool {
		si, sj := severityRank(sorted[i].Severity), severityRank(sorted[j].Severity)
		if si != sj {
			return si < sj
		}
		return sorted[i].ID < sorted[j].ID
	})

	var currentSeverity event.Severity
	first := true
	for _, d := range sorted {
		if first || d.Severity != currentSeverity {
			fmt.Fprintf(&b, "## %s\n\n", severityHeading(d.Severity))
			currentSeverity = d.Severity
			first = false
		}
		fmt.Fprintf(&b, "- **%s** (`%s`, source: %s)\n", d.Title, d.ID, d.Source)
		if len(d.Files) > 0 {
			fmt.Fprintf(&b, "  - Files: %s\n", strings.Join(quoteEach(d.Files), ", "))
		}
	}
	b.WriteString("\n")

	return b.String()
}

func quoteEach(files []string) []string {
	out := make([]string, len(files))
	for i, f := range files {
		out[i] = "`" + f + "`"
	}
	return out
}
