package output

import (
	"fmt"
	"sort"
	"strings"

	"github.com/jenaiz/pcke/internal/analysis"
)

// renderHistory generates the HISTORY.md content showing a timeline of files
// ordered by stability (most volatile first).
func renderHistory(nodes []analysis.KnowledgeNode) string {
	var b strings.Builder
	b.WriteString("# History\n\n")
	b.WriteString("> Auto-generated by `pcke sync`. Do not edit manually.\n\n")

	if len(nodes) == 0 {
		b.WriteString("No files analysed yet.\n")
		return b.String()
	}

	// Sort by stability ascending (most volatile first).
	sorted := make([]analysis.KnowledgeNode, len(nodes))
	copy(sorted, nodes)
	sort.Slice(sorted, func(i, j int) bool {
		return sorted[i].Stability < sorted[j].Stability
	})

	b.WriteString("## Most Volatile Files\n\n")
	b.WriteString("| File | Stability | Module |\n|------|-----------|--------|\n")
	limit := 20
	if len(sorted) < limit {
		limit = len(sorted)
	}
	for _, n := range sorted[:limit] {
		fmt.Fprintf(&b, "| `%s` | %.2f | %s |\n", n.FilePath, n.Stability, n.Module)
	}
	b.WriteString("\n")

	return b.String()
}
