package output

import (
	"fmt"
	"strings"

	"github.com/jenaiz/pcke/internal/analysis"
)

// renderModulePage generates a per-module Markdown page listing the files
// in the module with their classification and stability.
func renderModulePage(module string, nodes []analysis.KnowledgeNode) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Module: %s\n\n", module)
	b.WriteString("> Auto-generated by `pcke sync`. Do not edit manually.\n\n")

	b.WriteString("## Files\n\n")
	b.WriteString("| File | Class | Language | Stability |\n")
	b.WriteString("|------|-------|----------|-----------|\n")
	for _, n := range nodes {
		fmt.Fprintf(&b, "| `%s` | %s | %s | %.2f |\n", n.FilePath, n.Class, n.Language, n.Stability)
	}
	b.WriteString("\n")

	return b.String()
}
