package migrate

import (
	"bytes"
	"context"
	"fmt"

	"github.com/jenaiz/pcke/internal/kdb/tx"
)

// legacyElPrefix is the byte prefix of v0.9.x evolution-log records.
const legacyElPrefix = "el:"

// V0014RetireEvolutionLog returns the migration that removes legacy
// el: evolution-log records.
//
// Rationale (PRD v5.2 §3.6):
//
// EvolutionLog v0.9.x captured only file renames — a shallow signal that
// is regenerated automatically by every `pcke scan` from git history.
// The new typed-event schema captures evolution as the version chain on
// Entity events (latest + supersedes pointers), which is richer and
// always fresh. Keeping the stale el: records around adds storage with
// no read benefit; the next scan will rebuild whatever evolution data
// is still relevant from the git log directly.
//
// The migration is destructive on el: records ONLY: kn:, rel:, nt: are
// untouched (those are translated by 0011/0012/0013 and preserved).
// el: data is non-destructive in practice because it is auto-derived;
// the next scan replaces it.
//
// Idempotent: a second run finds no el: keys and is a no-op. Engine-
// level idempotency at schema-version 14 means subsequent invocations
// of the engine skip this migration entirely.
func V0014RetireEvolutionLog() Migration {
	return Migration{
		Version:     14,
		Description: "retire legacy el: evolution-log records (regenerated by next scan)",
		Migrate:     migrateRetireEvolutionLog,
	}
}

func migrateRetireEvolutionLog(ctx context.Context, db UpdateDB) error {
	keys, err := collectLegacyElKeys(ctx, db)
	if err != nil {
		return fmt.Errorf("migrate 0014: collect: %w", err)
	}
	if len(keys) == 0 {
		return nil
	}
	for start := 0; start < len(keys); start += knBatchSize {
		if err := ctx.Err(); err != nil {
			return fmt.Errorf("migrate 0014: cancelled: %w", err)
		}
		end := start + knBatchSize
		if end > len(keys) {
			end = len(keys)
		}
		if err := deleteElBatch(ctx, db, keys[start:end]); err != nil {
			return fmt.Errorf("migrate 0014: batch %d-%d: %w", start, end, err)
		}
	}
	return nil
}

func collectLegacyElKeys(ctx context.Context, db UpdateDB) ([][]byte, error) {
	var keys [][]byte
	err := db.View(ctx, func(rtx *tx.ReadTx) error {
		cursor := rtx.Cursor()
		if !cursor.Seek([]byte(legacyElPrefix)) {
			return nil
		}
		for cursor.Valid() {
			key := cursor.Key()
			if !bytes.HasPrefix(key, []byte(legacyElPrefix)) {
				break
			}
			// Cursor.Key returns a copy already, so this slice is safe
			// to retain past the next Next() call.
			keys = append(keys, key)
			cursor.Next()
		}
		return nil
	})
	return keys, err
}

func deleteElBatch(ctx context.Context, db UpdateDB, keys [][]byte) error {
	return db.Update(ctx, func(wtx *tx.WriteTx) error {
		for _, k := range keys {
			if err := wtx.Delete(k); err != nil {
				return fmt.Errorf("delete %q: %w", k, err)
			}
		}
		return nil
	})
}
